name: denguego
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  google_maps_flutter: ^2.0.1
  http: ^0.13.0
  json_serializable: ^3.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

